### PR TITLE
Larger recent app thumbs for moto xoom wingray

### PR DESCRIPTION
**Pull request by zigackly**
Using the xoom's large screen space to better effect. 

A similar modification could also work for stingray & everest.

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.com/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.com/wiki/Howto:_Gerrit

Thanks!

**Comment by SteadyHawkin** [comment]
If you could push this commit to gerrit as opposed to GitHub directly it would be much appreciated. Also, this may be better used as a frameworks patch.

**Comment by zigackly** [comment]
Thanks, I am just learning how to do that.

I did initially make the changes to the framework for all devices, but
decided to move them to the overlay for wingray so that I could try getting
them included in CM for the Xoom.

I can do it as a patch if you think that's better, but this does look
pretty good on the Xoom. Happy to listen to your advice though.

**Comment by zigackly** [comment]
http://review.cyanogenmod.com/#/c/24045/

**Pull request closed without merging**
